# Generated by Django 5.2.11 on 2026-04-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
    ]
